name: Docker Image Build and Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and publish a docker image
      env:
        REPO: signalsciences/sigsci-nginx-ingress-controller
      run: |
        TAG=$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")
        docker build . --file Dockerfile --build-arg NGINX_INGRESS_VERSION=${TAG} --build-arg --tag ${REPO}:${TAG}
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${REPO}:${TAG}
